//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAtb_user
    {
        public int id { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string TitleID { get; set; }
        public string FirstNameTh { get; set; }
        public string LastNameTh { get; set; }
        public string FirstNameEn { get; set; }
        public string LastNameEn { get; set; }
        public string StatusID { get; set; }
        public string IDCard { get; set; }
        public string TIN { get; set; }
        public string SexID { get; set; }
        public string BloodID { get; set; }
        public string ReligionID { get; set; }
        public string EthnicityID { get; set; }
        public string NationalityID { get; set; }
        public string MaritalStatusID { get; set; }
        public string Birthday { get; set; }
        public string RetireDate { get; set; }
        public string StartWorkDate { get; set; }
        public string ProbationDate { get; set; }
        public string Remuneration { get; set; }
        public string WorkingTypeID { get; set; }
        public string FingerScan { get; set; }
        public string CardScan { get; set; }
        public string SalaryLevel { get; set; }
        public string SalaryStep { get; set; }
        public string Salary { get; set; }
        public string HomeAddr { get; set; }
        public string HomeSubDistrictID { get; set; }
        public string HomeDistrictID { get; set; }
        public string HomeProvinceID { get; set; }
        public string HomeZipCode { get; set; }
        public string CurrAddr { get; set; }
        public string CurrSubDistrictID { get; set; }
        public string CurrDistrictID { get; set; }
        public string CurrProvinceID { get; set; }
        public string CurrZipCode { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string Avatar { get; set; }
        public string IsActive { get; set; }
        public string CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string UserTID { get; set; }
        public string AgentPoAID { get; set; }
        public string ProvidentFundNo { get; set; }
        public string ProvidentFundDate { get; set; }
        public string CrpID { get; set; }
        public string CrpTID { get; set; }
        public string ResignID { get; set; }
        public string ResignRemark { get; set; }
        public string ResignDate { get; set; }
        public string EmpowerID { get; set; }
        public string EmpowerDivID { get; set; }
        public string EmpowerDepID { get; set; }
        public string EmpowerSecID { get; set; }
        public string AgentPoID { get; set; }
        public string AgentDivID { get; set; }
        public string AgentDepID { get; set; }
        public string AgentSecID { get; set; }
        public string IsGPALower250 { get; set; }
        public string IsToeicLower300 { get; set; }
        public string IsAgeOver35 { get; set; }
        public string AgentMpID { get; set; }
        public string FileAttach1 { get; set; }
        public string FileAttach2 { get; set; }
    }
}
