
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAT.HR.Data.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ActionType
{

    public int ActID { get; set; }

    public string ActName { get; set; }

    public string ActType { get; set; }

    public string ActPos { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string CreateBy { get; set; }

    public Nullable<System.DateTime> ModifyDate { get; set; }

    public string ModifyBy { get; set; }

}

}
