//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Accident
    {
        public int ActID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ActDate { get; set; }
        public string ActPlace { get; set; }
        public string ActDesc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tb_User tb_User { get; set; }
    }
}
