//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Benefit_Cremation
    {
        public int BcID { get; set; }
        public int UserID { get; set; }
        public string BcYear { get; set; }
        public Nullable<int> MID { get; set; }
        public string BcMemberNo { get; set; }
        public string BcBeneficiary1 { get; set; }
        public string BcBeneficiary2 { get; set; }
        public string BcBeneficiary3 { get; set; }
        public string BcBeneficiary4 { get; set; }
        public string BcBeneficiary5 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_Member_Type tb_Member_Type { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
