//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Benefit_Calculate_Type
    {
        public int BntcID { get; set; }
        public Nullable<int> BntID { get; set; }
        public string BntcName { get; set; }
    
        public virtual tb_Benefit_Replacement_Type tb_Benefit_Replacement_Type { get; set; }
    }
}
