//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Benefit_Child_Fund
    {
        public int BcfID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BcfYear { get; set; }
        public string BcfName { get; set; }
        public Nullable<decimal> BcfIDCard { get; set; }
        public Nullable<System.DateTime> BcfBirthDate { get; set; }
        public Nullable<System.DateTime> BcfExpireDate { get; set; }
        public Nullable<decimal> BcfAmout { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_User tb_User { get; set; }
    }
}
