//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Benefit_Home_Rental
    {
        public int BhrID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BhrYear { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> BhrLevel { get; set; }
        public Nullable<int> BhrStep { get; set; }
        public Nullable<System.DateTime> BhrStartDate { get; set; }
        public Nullable<System.DateTime> BhrEndDate { get; set; }
        public Nullable<decimal> BhrAmout { get; set; }
        public string BhrRemark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_Part_Type tb_Part_Type { get; set; }
        public virtual tb_Rent_Type tb_Rent_Type { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
