//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Benefit_Provident_Fund
    {
        public int BpID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BpYear { get; set; }
        public Nullable<System.DateTime> BpDateChangeFund { get; set; }
        public Nullable<int> BpAccumFundCuID { get; set; }
        public Nullable<int> BpAssoFundCuID { get; set; }
        public string BpBeneficiary1 { get; set; }
        public string BpBeneficiary2 { get; set; }
        public string BpBeneficiary3 { get; set; }
        public string BpBeneficiary4 { get; set; }
        public string BpBeneficiary5 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_Accumulative_Fund tb_Accumulative_Fund { get; set; }
        public virtual tb_Accumulative_Fund tb_Accumulative_Fund1 { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
