//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Form_Master
    {
        public int FormMasterID { get; set; }
        public string FormMasterName { get; set; }
        public string FormMasterDesc { get; set; }
        public string TableName { get; set; }
    }
}
