//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Move_Man_Power_Detail
    {
        public int MopDID { get; set; }
        public int MopID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> MopNewPoID { get; set; }
        public Nullable<int> MopOldPoID { get; set; }
        public Nullable<int> PoTAgentID { get; set; }
        public Nullable<int> AgentMpID { get; set; }
        public string MovRemark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_Man_Power tb_Man_Power { get; set; }
        public virtual tb_Man_Power tb_Man_Power1 { get; set; }
        public virtual tb_Move_Man_Power_Head tb_Move_Man_Power_Head { get; set; }
    }
}
