//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Move_Man_Power_Head
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Move_Man_Power_Head()
        {
            this.tb_Move_Man_Power_Detail = new HashSet<tb_Move_Man_Power_Detail>();
        }
    
        public int MopID { get; set; }
        public Nullable<int> UserTID { get; set; }
        public Nullable<int> MtID { get; set; }
        public string MopYear { get; set; }
        public string MopBookCmd { get; set; }
        public Nullable<System.DateTime> MopDateCmd { get; set; }
        public Nullable<System.DateTime> MopDateEff { get; set; }
        public string MopSignatory { get; set; }
        public string MopPathFile { get; set; }
        public Nullable<bool> MopStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Move_Man_Power_Detail> tb_Move_Man_Power_Detail { get; set; }
    }
}
