//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Menu_Role
    {
        public int RoleID { get; set; }
        public int MenuID { get; set; }
        public Nullable<bool> R_View { get; set; }
        public Nullable<bool> R_Add { get; set; }
        public Nullable<bool> R_Edit { get; set; }
        public Nullable<bool> R_Delete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_Menu tb_Menu { get; set; }
        public virtual tb_Role tb_Role { get; set; }
    }
}
