//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Process_History
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Process_Year { get; set; }
        public Nullable<int> Process_Old_Level { get; set; }
        public Nullable<decimal> Process_Old_Step { get; set; }
        public Nullable<decimal> Process_Old_Salary { get; set; }
        public Nullable<int> Process_New_Level { get; set; }
        public Nullable<decimal> Process_New_Step { get; set; }
        public Nullable<decimal> Process_New_Salary { get; set; }
        public Nullable<decimal> Process_Level_Increase { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_User tb_User { get; set; }
    }
}
