//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Role
    {
        public int PerID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual tb_GroupRole tb_GroupRole { get; set; }
        public virtual tb_Menu tb_Menu { get; set; }
    }
}
