//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Salary_Increase_Header
    {
        public int HeaderID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> UpLevel { get; set; }
        public Nullable<decimal> UpStep { get; set; }
        public string BookCmd { get; set; }
        public Nullable<System.DateTime> DateCmd { get; set; }
        public Nullable<System.DateTime> DateEff { get; set; }
        public string PathFile { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
