//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Trans_Step_Tracking
    {
        public int TrackingID { get; set; }
        public int FormMasterID { get; set; }
        public int FormHeaderID { get; set; }
        public int FormID { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<System.DateTime> LastApproveDate { get; set; }
        public string Accept { get; set; }
        public Nullable<int> StepNo { get; set; }
        public string StepName { get; set; }
        public string Comment { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Overdue { get; set; }
        public Nullable<int> Approver_MpID { get; set; }
        public Nullable<int> Approver_UserID { get; set; }
        public string Approver_FullName { get; set; }
        public string Approver_DivName { get; set; }
        public string Approver_DepName { get; set; }
        public string Approver_SecName { get; set; }
        public string Approver_PoName { get; set; }
        public Nullable<int> TransStepApproverID { get; set; }
        public Nullable<int> TransStepID { get; set; }
    }
}
