//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TimeAttendance
    {
        public int TaID { get; set; }
        public Nullable<int> TaTID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Std_TimeIn { get; set; }
        public Nullable<System.DateTime> Act_TimeIn { get; set; }
        public Nullable<System.DateTime> Std_TimeOut { get; set; }
        public Nullable<System.DateTime> Act_TimeOut { get; set; }
        public Nullable<System.DateTime> Adj_TimeIn { get; set; }
        public Nullable<System.DateTime> Adj_TimeOut { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_TimeAttendance_Type tb_TimeAttendance_Type { get; set; }
    }
}
