//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Trans_Step_Approver
    {
        public int ID { get; set; }
        public Nullable<int> StepID { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public Nullable<int> MpID { get; set; }
        public Nullable<int> Accept { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public string Comment { get; set; }
    }
}
