//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Education
    {
        public int UeID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EduID { get; set; }
        public Nullable<int> DegID { get; set; }
        public Nullable<int> MajID { get; set; }
        public string UeInstituteName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<System.DateTime> UeGraduationDate { get; set; }
        public Nullable<decimal> UeGPA { get; set; }
        public Nullable<bool> UeEduOfficial { get; set; }
        public Nullable<bool> UeEduOfficialLevel { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_Country tb_Country { get; set; }
        public virtual tb_Degree tb_Degree { get; set; }
        public virtual tb_Education tb_Education { get; set; }
        public virtual tb_Major tb_Major { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
