//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Position
    {
        public int UpID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ActID { get; set; }
        public string UpCmd { get; set; }
        public Nullable<int> PoTID { get; set; }
        public Nullable<int> DepID { get; set; }
        public Nullable<int> PoID { get; set; }
        public Nullable<int> PoAID { get; set; }
        public string UpLevel { get; set; }
        public Nullable<decimal> UpSalary { get; set; }
        public Nullable<System.DateTime> UpCmdDate { get; set; }
        public Nullable<System.DateTime> UpForceDate { get; set; }
        public string UpRemark { get; set; }
        public string UpPathFile { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_Action_Type tb_Action_Type { get; set; }
        public virtual tb_Department tb_Department { get; set; }
        public virtual tb_Position_Type tb_Position_Type { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
