//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_History
    {
        public int UhID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> UhEditDate { get; set; }
        public Nullable<int> OldTiID { get; set; }
        public string OldFirstNameTh { get; set; }
        public string OldLastNameTh { get; set; }
        public string OldFirstNameEn { get; set; }
        public string OldLastNameEn { get; set; }
        public Nullable<int> NewTiID { get; set; }
        public string NewFirstNameTh { get; set; }
        public string NewLastNameTh { get; set; }
        public string NewFirstNameEn { get; set; }
        public string NewLastNameEn { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> UhStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_User tb_User { get; set; }
    }
}
