//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Family
    {
        public int UfID { get; set; }
        public int UserID { get; set; }
        public string UfName { get; set; }
        public Nullable<decimal> UfCardID { get; set; }
        public Nullable<System.DateTime> UfDOB { get; set; }
        public Nullable<bool> UfLifeStatus { get; set; }
        public Nullable<bool> TdStatus { get; set; }
        public Nullable<int> PoID { get; set; }
        public Nullable<int> OcID { get; set; }
        public Nullable<System.DateTime> UfWeddingDate { get; set; }
        public Nullable<System.DateTime> DivorceDate { get; set; }
        public Nullable<bool> UfStudyStatus { get; set; }
        public Nullable<int> RecID { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<decimal> ChildEducationAmout { get; set; }
        public Nullable<decimal> ChildFundAmout { get; set; }
    
        public virtual tb_Marital_Status tb_Marital_Status { get; set; }
        public virtual tb_Occupation tb_Occupation { get; set; }
        public virtual tb_Recieve_Type tb_Recieve_Type { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
