//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Insignia
    {
        public int UiID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> InsID { get; set; }
        public string UiYear { get; set; }
        public string UiBook { get; set; }
        public string UiPart { get; set; }
        public string UiPage { get; set; }
        public Nullable<System.DateTime> UiRecDate { get; set; }
        public Nullable<System.DateTime> UiRetDate { get; set; }
        public string UiCmd { get; set; }
        public string UiPartFile { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual tb_Insignia tb_Insignia { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
