//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_User()
        {
            this.tb_Benefit_Cremation = new HashSet<tb_Benefit_Cremation>();
            this.tb_Benefit_Death_Replacement = new HashSet<tb_Benefit_Death_Replacement>();
            this.tb_Benefit_Death_Subsidy = new HashSet<tb_Benefit_Death_Subsidy>();
            this.tb_Benefit_Home_Rental = new HashSet<tb_Benefit_Home_Rental>();
            this.tb_Benefit_Loan = new HashSet<tb_Benefit_Loan>();
            this.tb_Benefit_Medical = new HashSet<tb_Benefit_Medical>();
            this.tb_Benefit_Other_Welfare = new HashSet<tb_Benefit_Other_Welfare>();
            this.tb_Benefit_Provident_Fund = new HashSet<tb_Benefit_Provident_Fund>();
            this.tb_Evaluation = new HashSet<tb_Evaluation>();
            this.tb_Man_Power = new HashSet<tb_Man_Power>();
            this.tb_Process_History = new HashSet<tb_Process_History>();
            this.tb_Time_Attendance = new HashSet<tb_Time_Attendance>();
            this.tb_Training_Course = new HashSet<tb_Training_Course>();
            this.tb_User_Certificate = new HashSet<tb_User_Certificate>();
            this.tb_User_Education = new HashSet<tb_User_Education>();
            this.tb_User_Excellent = new HashSet<tb_User_Excellent>();
            this.tb_User_Family = new HashSet<tb_User_Family>();
            this.tb_User_History = new HashSet<tb_User_History>();
            this.tb_User_Position = new HashSet<tb_User_Position>();
            this.tb_User_Skill = new HashSet<tb_User_Skill>();
            this.tb_User_Training = new HashSet<tb_User_Training>();
            this.tb_Working_Shift = new HashSet<tb_Working_Shift>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string FirstNameTh { get; set; }
        public string LastNameTh { get; set; }
        public string FirstNameEn { get; set; }
        public string LastNameEn { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<decimal> IDCard { get; set; }
        public Nullable<decimal> TIN { get; set; }
        public Nullable<int> SexID { get; set; }
        public Nullable<int> BloodID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> EthnicityID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> RetireDate { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
        public Nullable<System.DateTime> ProbationDate { get; set; }
        public string Remuneration { get; set; }
        public Nullable<int> WorkingTypeID { get; set; }
        public string FingerScan { get; set; }
        public string CardScan { get; set; }
        public Nullable<int> SalaryLevel { get; set; }
        public Nullable<decimal> SalaryStep { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> EmpowerID { get; set; }
        public Nullable<int> EmpowerDepID { get; set; }
        public Nullable<int> AgentDepID { get; set; }
        public Nullable<int> AgentPoID { get; set; }
        public string HomeAddr { get; set; }
        public Nullable<int> HomeSubDistrictID { get; set; }
        public Nullable<int> HomeDistrictID { get; set; }
        public Nullable<int> HomeProvinceID { get; set; }
        public Nullable<int> HomeZipCode { get; set; }
        public string CurrAddr { get; set; }
        public Nullable<int> CurrSubDistrictID { get; set; }
        public Nullable<int> CurrDistrictID { get; set; }
        public Nullable<int> CurrProvinceID { get; set; }
        public Nullable<int> CurrZipCode { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<int> UserTID { get; set; }
        public Nullable<int> AgentPoAID { get; set; }
        public string ProvidentFundNo { get; set; }
        public Nullable<System.DateTime> ProvidentFundDate { get; set; }
        public Nullable<int> CrpID { get; set; }
        public Nullable<int> CrpTID { get; set; }
        public Nullable<int> ResignID { get; set; }
        public string ResignRemark { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<bool> IsGPALower250 { get; set; }
        public Nullable<bool> IsToeicLower300 { get; set; }
        public Nullable<bool> IsAgeOver35 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Benefit_Cremation> tb_Benefit_Cremation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Benefit_Death_Replacement> tb_Benefit_Death_Replacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Benefit_Death_Subsidy> tb_Benefit_Death_Subsidy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Benefit_Home_Rental> tb_Benefit_Home_Rental { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Benefit_Loan> tb_Benefit_Loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Benefit_Medical> tb_Benefit_Medical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Benefit_Other_Welfare> tb_Benefit_Other_Welfare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Benefit_Provident_Fund> tb_Benefit_Provident_Fund { get; set; }
        public virtual tb_Blood_Type tb_Blood_Type { get; set; }
        public virtual tb_Cripple tb_Cripple { get; set; }
        public virtual tb_Cripple_Type tb_Cripple_Type { get; set; }
        public virtual tb_Empower tb_Empower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Evaluation> tb_Evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Man_Power> tb_Man_Power { get; set; }
        public virtual tb_Marital_Status tb_Marital_Status { get; set; }
        public virtual tb_Nationality tb_Nationality { get; set; }
        public virtual tb_Nationality tb_Nationality1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Process_History> tb_Process_History { get; set; }
        public virtual tb_Religion tb_Religion { get; set; }
        public virtual tb_Resign_Type tb_Resign_Type { get; set; }
        public virtual tb_Sex tb_Sex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Time_Attendance> tb_Time_Attendance { get; set; }
        public virtual tb_Title tb_Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Training_Course> tb_Training_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User_Certificate> tb_User_Certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User_Education> tb_User_Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User_Excellent> tb_User_Excellent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User_Family> tb_User_Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User_History> tb_User_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User_Position> tb_User_Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User_Skill> tb_User_Skill { get; set; }
        public virtual tb_User_Type tb_User_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User_Training> tb_User_Training { get; set; }
        public virtual tb_User_Status tb_User_Status { get; set; }
        public virtual tb_Working_Type tb_Working_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Working_Shift> tb_Working_Shift { get; set; }
    }
}
