//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Working_Time
    {
        public int WID { get; set; }
        public Nullable<int> WtID { get; set; }
        public string WorkDay { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    }
}
