//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Agent_Position_bak
    {
        public int MpID { get; set; }
        public string PoName { get; set; }
        public string FullSectionName { get; set; }
        public Nullable<int> PoID { get; set; }
    }
}
