//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Benefit_Loan
    {
        public int BlID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BlYear { get; set; }
        public Nullable<int> BID { get; set; }
        public string BName { get; set; }
        public string LtName { get; set; }
        public Nullable<int> LtID { get; set; }
        public Nullable<decimal> BlAccountNo { get; set; }
        public Nullable<System.DateTime> BlStartDate { get; set; }
        public Nullable<System.DateTime> BlEndDate { get; set; }
        public Nullable<System.DateTime> BlCloseDate { get; set; }
        public Nullable<decimal> BlPeriod { get; set; }
        public Nullable<decimal> BlPeriodPay { get; set; }
        public Nullable<decimal> BISummaryAmout { get; set; }
        public string BlRemark { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<decimal> Outstanding { get; set; }
        public Nullable<int> BlStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
