//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Benefit_Medical
    {
        public int BmID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BmYear { get; set; }
        public Nullable<int> ClID { get; set; }
        public string ClName { get; set; }
        public Nullable<int> RecID { get; set; }
        public string RecFullName { get; set; }
        public Nullable<decimal> BmCardID { get; set; }
        public Nullable<System.DateTime> BmDate { get; set; }
        public Nullable<decimal> BmAmoutService { get; set; }
        public Nullable<decimal> BmAmoutCare { get; set; }
        public string BmRemark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
