//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Capability
    {
        public Nullable<int> CapYear { get; set; }
        public int CapID { get; set; }
        public Nullable<int> CapTID { get; set; }
        public string CapTName { get; set; }
        public Nullable<int> CapGID { get; set; }
        public string CapGName { get; set; }
        public string TableName { get; set; }
        public Nullable<int> CapGTID { get; set; }
        public string CapGTName { get; set; }
    }
}
