//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Course
    {
        public int CourseID { get; set; }
        public string CourseNo { get; set; }
        public Nullable<int> CourseTID { get; set; }
        public string CourseTName { get; set; }
        public string CourseName { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public string TrainerName { get; set; }
        public string Location { get; set; }
        public string Certificate { get; set; }
        public string CourseDesc { get; set; }
        public string PathFile { get; set; }
        public string Status { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
