//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Child
    {
        public int UfID { get; set; }
        public int UserID { get; set; }
        public string UfName { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
