//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Move_Level_Detail
    {
        public int MlID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FullName { get; set; }
        public Nullable<decimal> MlLevelOld { get; set; }
        public Nullable<decimal> MlStepOld { get; set; }
        public Nullable<decimal> MlSalaryOld { get; set; }
        public Nullable<decimal> MlLevelNew { get; set; }
        public Nullable<decimal> MlStepNew { get; set; }
        public Nullable<decimal> MlSalaryNew { get; set; }
        public string MlRemark { get; set; }
    }
}
