//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Move_Level_Head
    {
        public int MlID { get; set; }
        public Nullable<int> MlYear { get; set; }
        public string MlBookCmd { get; set; }
        public Nullable<System.DateTime> MlDateCmd { get; set; }
        public string MlSignatory { get; set; }
        public string MIPathFile { get; set; }
        public Nullable<int> MlStatus { get; set; }
        public Nullable<int> MlTotal { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
