//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Move_Man_Power_Head
    {
        public int MopID { get; set; }
        public Nullable<int> MtID { get; set; }
        public string MtName { get; set; }
        public Nullable<int> UserTID { get; set; }
        public string EmpTName { get; set; }
        public string MopYear { get; set; }
        public string MopBookCmd { get; set; }
        public Nullable<System.DateTime> MopDateCmd { get; set; }
        public Nullable<int> MopTotal { get; set; }
        public string MopSignatory { get; set; }
        public string MopPathFile { get; set; }
        public Nullable<bool> MopApproveStatus { get; set; }
        public Nullable<int> MopStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
