//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Organization1
    {
        public int MpID { get; set; }
        public string MpCode { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string DivName { get; set; }
        public string DepName { get; set; }
        public string SecName { get; set; }
        public string PoName { get; set; }
        public string FullNameTh { get; set; }
        public Nullable<int> TypeID { get; set; }
        public int DepLevel { get; set; }
        public string PathMpID { get; set; }
    }
}
