//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RoleMenuReport
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public int MenuID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string MenuName { get; set; }
        public int R_View { get; set; }
        public int R_Add { get; set; }
        public int R_Edit { get; set; }
        public int R_Delete { get; set; }
    }
}
