//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Trans_Step_Route
    {
        public int StepID { get; set; }
        public Nullable<int> FormMasterID { get; set; }
        public Nullable<int> FormHeaderID { get; set; }
        public Nullable<int> FormStepID { get; set; }
        public Nullable<int> NextStepID { get; set; }
        public Nullable<int> StepNo { get; set; }
        public string StepName { get; set; }
        public Nullable<int> ApproveType { get; set; }
        public string ExtendProc { get; set; }
        public Nullable<bool> IsNotifyAcceptNext { get; set; }
        public Nullable<bool> IsNotifyAcceptSelf { get; set; }
        public Nullable<bool> IsNotifyAcceptPrev { get; set; }
        public Nullable<bool> IsNotifyAcceptRequestor { get; set; }
        public Nullable<bool> IsNotifyAcceptCustom { get; set; }
        public Nullable<bool> IsNotifyRejectNext { get; set; }
        public Nullable<bool> IsNotifyRejectSelf { get; set; }
        public Nullable<bool> IsNotifyRejectPrev { get; set; }
        public Nullable<bool> IsNotifyRejectRequestor { get; set; }
        public Nullable<bool> IsNotifyRejectCustom { get; set; }
        public Nullable<bool> NotifyAcceptNextTemplateID { get; set; }
        public Nullable<bool> NotifyAcceptSelfTemplateID { get; set; }
        public Nullable<bool> NotifyAcceptPrevTemplateID { get; set; }
        public Nullable<bool> NotifyAcceptRequestorTemplateID { get; set; }
        public Nullable<bool> NotifyAcceptCustomTemplateID { get; set; }
        public Nullable<bool> NotifyRejectNextTemplateID { get; set; }
        public Nullable<bool> NotifyRejectSelfTemplateID { get; set; }
        public Nullable<bool> NotifyRejectPrevTemplateID { get; set; }
        public Nullable<bool> NotifyRejectRequestorTemplateID { get; set; }
        public Nullable<bool> NotifyRejectCustomTemplateID { get; set; }
        public string NotifyAcceptCustomMail { get; set; }
        public string NotifyRejectCustomMail { get; set; }
    }
}
