//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Trainning_Course
    {
        public int CourseID { get; set; }
        public string CourseNo { get; set; }
        public string CourseName { get; set; }
        public int UserID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> PoID { get; set; }
        public string PoCode { get; set; }
        public string PoName { get; set; }
    }
}
