//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Title
    {
        public int TiID { get; set; }
        public string TiFullName { get; set; }
        public string TiShortName { get; set; }
        public Nullable<bool> TiStatus { get; set; }
        public Nullable<int> SexID { get; set; }
        public string SexName { get; set; }
    }
}
