//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_User_Education
    {
        public int UeID { get; set; }
        public int UserID { get; set; }
        public string FullNameTH { get; set; }
        public string FullNameEn { get; set; }
        public Nullable<int> EduID { get; set; }
        public string EduName { get; set; }
        public Nullable<int> DegID { get; set; }
        public string DegName { get; set; }
        public Nullable<int> MajID { get; set; }
        public string MajName { get; set; }
        public string UeInstituteName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> UeGraduationDate { get; set; }
        public Nullable<decimal> UeGPA { get; set; }
        public Nullable<bool> UeEduOfficial { get; set; }
        public Nullable<bool> UeEduOfficialLevel { get; set; }
    }
}
