//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_User_History
    {
        public int UhID { get; set; }
        public int UserID { get; set; }
        public string FullNameTH { get; set; }
        public string FullNameEn { get; set; }
        public Nullable<System.DateTime> UhEditDate { get; set; }
        public Nullable<int> TiID { get; set; }
        public string TiFullName { get; set; }
        public string TiShortName { get; set; }
        public string UhFirstNameTH { get; set; }
        public string UhLastNameTH { get; set; }
        public string UhFirstNameEN { get; set; }
        public string UhLastNameEN { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> UhStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
