//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_User_Position
    {
        public int UpID { get; set; }
        public int UserID { get; set; }
        public string FullNameTH { get; set; }
        public string FullNameEn { get; set; }
        public Nullable<int> ActID { get; set; }
        public string ActName { get; set; }
        public string UpCmd { get; set; }
        public Nullable<int> PoTID { get; set; }
        public string PoTName { get; set; }
        public Nullable<int> DivID { get; set; }
        public string DivName { get; set; }
        public Nullable<int> DepID { get; set; }
        public string DepName { get; set; }
        public Nullable<int> SecID { get; set; }
        public string SecName { get; set; }
        public Nullable<int> PoID { get; set; }
        public string PoName { get; set; }
        public Nullable<int> PoAID { get; set; }
        public string PoAName { get; set; }
        public string UpLevel { get; set; }
        public Nullable<decimal> UpSalary { get; set; }
        public Nullable<System.DateTime> UpCmdDate { get; set; }
        public Nullable<System.DateTime> UpForceDate { get; set; }
        public string UpRemark { get; set; }
        public string UpPathFile { get; set; }
    }
}
