//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.HR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> UserTID { get; set; }
        public string UserTName { get; set; }
        public int DivID { get; set; }
        public string DivName { get; set; }
        public int DepID { get; set; }
        public string DepName { get; set; }
        public int SecID { get; set; }
        public string SecName { get; set; }
        public int PoID { get; set; }
        public string PoCode { get; set; }
        public string PoName { get; set; }
        public Nullable<int> SexID { get; set; }
        public string SexName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Avatar { get; set; }
    }
}
